"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "aws-alb-ingress-controller"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "ingress-system"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "aws-alb-ingress-controller"
    "helm":
      "parameters":
      - "name": "rbac.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::641456973426:role/testcognito_aws-alb-ingress-controller"
      - "name": "clusterName"
        "value": "testcognito"
      - "name": "awsVpcID"
        "value": "vpc-0503cb09e8aad6d2f"
      - "name": "awsRegion"
        "value": "us-west-2"
      - "name": "resources.limits.cpu"
        "value": "100m"
      - "name": "resources.limits.memory"
        "value": "300Mi"
      - "name": "resources.requests.cpu"
        "value": "100m"
      - "name": "resources.requests.memory"
        "value": "300Mi"
    "repoURL": "https://kubernetes-charts-incubator.storage.googleapis.com"
    "targetRevision": "1.0.2"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
